include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test

build:
  stage: build
  script:
    - rm -rf .git/modules/* ./docs ./libraries/fc
    - git submodule sync
    - git submodule update --init --recursive
    - rm -rf build
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
  artifacts:
    untracked: true
    paths:
      - build/libraries/
      - build/programs/
      - build/tests/
  tags:
    - builder

test:
  stage: test
  dependencies:
    - build
  script:
    - ./build/tests/betting_test --log_level=message
    - ./build/tests/chain_test --log_level=message
    - ./build/tests/cli_test --log_level=message
  tags:
    - builder