include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml

stages:
  - build
  - test

build:
  stage: build
  script:
    - rm -rf .git/modules/* ./docs ./libraries/fc
    - git submodule sync
    - git submodule update --init --recursive
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -DENABLE_COVERAGE_TESTING=true ..
    - make all_graphene_tests -j$(nproc)
  artifacts:
    untracked: true
    paths:
      - build/tests/all_graphene_tests
  tags:
    - builder

test:
  stage: test
  dependencies:
    - build
  script:
    - ./build/tests/all_graphene_tests --log_level=message
    - lcov --capture --directory ./build/ --output-file ./build/coverage.tmp.info
    - lcov --remove ./build/coverage.tmp.info "/usr/*" --output-file ./build/coverage.info
    - genhtml --output-directory ./build/coverage ./build/coverage.info
  artifacts:
    untracked: true
    paths:
      - build/coverage/
      - build/coverage.info
      - build/coverage.tmp.info
  tags:
    - builder
