stages:
  - build
  - test

build:
  stage: build
  script:
    - git submodule update --init --recursive
    - cmake .
    - make -j$(nproc)
  artifacts:
    untracked: true
    paths:
      - libraries/
      - programs/
      - tests/
  tags:
    - builder
    
test:
  stage: test
  dependencies: 
    - build
  script:
    - ./tests/betting_test
    - ./tests/chain_test
  tags:
    - builder