stages:
  - build
  - test

build:
  stage: build
  script:
    - git submodule update --init --recursive
    - cmake .
    - make -j$(nproc)
  tags:
    - builder
    
test:
  stage: test
  script:
    - ./test/betting_test
    - ./test/chain_test
  tags:
    - builder