stages:
  - build
  - test

build:
  stage: build
  script:
    - git submodule update --init --recursive
    - cmake .
    - make -j$(nproc)
  cache:
    paths:
      - libraries/
      - programs/
      - test/
  tags:
    - builder
    
test:
  stage: test
  script:
    - ./tests/betting_test
    - ./tests/chain_test
  tags:
    - builder