include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - git submodule sync
    - git submodule update --init --recursive
    - cmake .
    - make -j$(nproc)
  artifacts:
    untracked: true
    paths:
      - libraries/
      - programs/
      - tests/
  tags:
    - builder
    
test:
  stage: test
  dependencies: 
    - build
  script:
    - ./tests/betting_test
    - ./tests/chain_test
    - ./tests/cli_test
  tags:
    - builder

deploy-rng:
  stage: deploy
  dependencies: 
    - build
  script:
    - mv ./programs/witness_node/witness_node /tmp
    - ansible-playbook /usr/local/bin/update-witness.yml
    - sh /usr/local/bin/update-info.sh
    - sh /usr/local/bin/cleanup.sh
  when: manual
